// Generated by `npm run i18n:sync` — do not edit by hand.
//
// Metro cannot read a directory at runtime, so the locale files that exist on
// disk are listed here. Adding a translation is: copy `locales/en.json`,
// translate the values, save it as `locales/<code>.json`, run `npm run i18n:sync`.

export type LocaleCode = 'en';

export const registeredLocales: Record<string, Record<string, unknown>> = {};
