// Generated by `npm run push:copy` — do not edit by hand.
//
// The words a notification shows, per language, taken from src/i18n/locales.
// A language the recipient has not chosen, or one that is missing a line,
// falls back to English rather than showing nothing.
export type PushKind = "new_match" | "new_message" | "moderation_status" | "safety_alert" | "product_notice";

export const PUSH_COPY: Record<string, Record<PushKind, { title: string; body: string }>> = {
  "ar": {
    "new_match": {
      "title": "إنه Bind!",
      "body": "افتح Binder لرؤية التوافق الجديد."
    },
    "new_message": {
      "title": "رسالة جديدة",
      "body": "افتح Binder لمتابعة المحادثة."
    },
    "moderation_status": {
      "title": "تمت مراجعة الصورة",
      "body": "هناك جديد بشأن مراجعة صورة ملفك الشخصي."
    },
    "safety_alert": {
      "title": "تنبيه أمان",
      "body": "افتح Binder للاطلاع على تنبيه بخصوص حسابك."
    },
    "product_notice": {
      "title": "جديد في Binder",
      "body": "افتح Binder لترى ما الذي تغيّر."
    }
  },
  "de": {
    "new_match": {
      "title": "Ein Bind!",
      "body": "Öffne Binder und sieh dir dein neues Match an."
    },
    "new_message": {
      "title": "Neue Nachricht",
      "body": "Öffne Binder, um weiterzuschreiben."
    },
    "moderation_status": {
      "title": "Foto geprüft",
      "body": "Zur Prüfung deines Profilfotos gibt es Neues."
    },
    "safety_alert": {
      "title": "Sicherheitshinweis",
      "body": "Öffne Binder für einen Hinweis zu deinem Konto."
    },
    "product_notice": {
      "title": "Neu in Binder",
      "body": "Öffne Binder und sieh, was sich geändert hat."
    }
  },
  "en": {
    "new_match": {
      "title": "It's a Bind",
      "body": "Open Binder to see your new match."
    },
    "new_message": {
      "title": "New message",
      "body": "Open Binder to continue the conversation."
    },
    "moderation_status": {
      "title": "Photo update",
      "body": "Your profile photo review has an update."
    },
    "safety_alert": {
      "title": "Binder safety notice",
      "body": "Open Binder to review an account safety update."
    },
    "product_notice": {
      "title": "Binder update",
      "body": "Open Binder to see what changed."
    }
  },
  "es": {
    "new_match": {
      "title": "¡Es un Bind!",
      "body": "Abre Binder para ver tu nuevo match."
    },
    "new_message": {
      "title": "Nuevo mensaje",
      "body": "Abre Binder para seguir la conversación."
    },
    "moderation_status": {
      "title": "Foto revisada",
      "body": "Hay novedades sobre la revisión de tu foto de perfil."
    },
    "safety_alert": {
      "title": "Aviso de seguridad",
      "body": "Abre Binder para ver un aviso sobre tu cuenta."
    },
    "product_notice": {
      "title": "Novedades en Binder",
      "body": "Abre Binder para ver qué ha cambiado."
    }
  },
  "fr": {
    "new_match": {
      "title": "C'est un Bind !",
      "body": "Ouvrez Binder pour voir votre nouveau match."
    },
    "new_message": {
      "title": "Nouveau message",
      "body": "Ouvrez Binder pour poursuivre la conversation."
    },
    "moderation_status": {
      "title": "Photo vérifiée",
      "body": "La vérification de votre photo de profil a avancé."
    },
    "safety_alert": {
      "title": "Avis de sécurité",
      "body": "Ouvrez Binder pour un avis concernant votre compte."
    },
    "product_notice": {
      "title": "Nouveautés Binder",
      "body": "Ouvrez Binder pour voir ce qui a changé."
    }
  },
  "hi": {
    "new_match": {
      "title": "यह एक Bind है!",
      "body": "अपना नया मैच देखने के लिए Binder खोलें।"
    },
    "new_message": {
      "title": "नया संदेश",
      "body": "बातचीत जारी रखने के लिए Binder खोलें।"
    },
    "moderation_status": {
      "title": "फ़ोटो जाँची गई",
      "body": "आपकी प्रोफ़ाइल फ़ोटो की जाँच पर अपडेट है।"
    },
    "safety_alert": {
      "title": "सुरक्षा सूचना",
      "body": "अपने खाते से जुड़ी सूचना देखने के लिए Binder खोलें।"
    },
    "product_notice": {
      "title": "Binder में नया",
      "body": "क्या बदला है यह देखने के लिए Binder खोलें।"
    }
  },
  "id": {
    "new_match": {
      "title": "Ini Bind!",
      "body": "Buka Binder untuk melihat match barumu."
    },
    "new_message": {
      "title": "Pesan baru",
      "body": "Buka Binder untuk melanjutkan percakapan."
    },
    "moderation_status": {
      "title": "Foto ditinjau",
      "body": "Ada kabar tentang peninjauan foto profilmu."
    },
    "safety_alert": {
      "title": "Pemberitahuan keamanan",
      "body": "Buka Binder untuk melihat pemberitahuan tentang akunmu."
    },
    "product_notice": {
      "title": "Yang baru di Binder",
      "body": "Buka Binder untuk melihat apa yang berubah."
    }
  },
  "it": {
    "new_match": {
      "title": "È un Bind!",
      "body": "Apri Binder per vedere il tuo nuovo match."
    },
    "new_message": {
      "title": "Nuovo messaggio",
      "body": "Apri Binder per continuare la conversazione."
    },
    "moderation_status": {
      "title": "Foto verificata",
      "body": "Ci sono novità sulla verifica della tua foto profilo."
    },
    "safety_alert": {
      "title": "Avviso di sicurezza",
      "body": "Apri Binder per leggere un avviso sul tuo account."
    },
    "product_notice": {
      "title": "Novità su Binder",
      "body": "Apri Binder per vedere cosa è cambiato."
    }
  },
  "ja": {
    "new_match": {
      "title": "新しいBind！",
      "body": "Binderを開いて新しいマッチを見てみましょう。"
    },
    "new_message": {
      "title": "新しいメッセージ",
      "body": "Binderを開いて会話を続けましょう。"
    },
    "moderation_status": {
      "title": "写真の確認",
      "body": "プロフィール写真の確認に進展があります。"
    },
    "safety_alert": {
      "title": "安全に関するお知らせ",
      "body": "アカウントに関するお知らせがあります。"
    },
    "product_notice": {
      "title": "Binderの新着",
      "body": "変更点をBinderで確認してみましょう。"
    }
  },
  "ko": {
    "new_match": {
      "title": "Bind 성사!",
      "body": "Binder를 열어 새로운 매치를 확인해 보세요."
    },
    "new_message": {
      "title": "새 메시지",
      "body": "Binder를 열어 대화를 이어가세요."
    },
    "moderation_status": {
      "title": "사진 검토",
      "body": "프로필 사진 검토에 새 소식이 있습니다."
    },
    "safety_alert": {
      "title": "안전 알림",
      "body": "계정 관련 알림을 Binder에서 확인하세요."
    },
    "product_notice": {
      "title": "Binder 새 소식",
      "body": "무엇이 바뀌었는지 Binder에서 확인해 보세요."
    }
  },
  "nl": {
    "new_match": {
      "title": "Een Bind!",
      "body": "Open Binder om je nieuwe match te zien."
    },
    "new_message": {
      "title": "Nieuw bericht",
      "body": "Open Binder om verder te praten."
    },
    "moderation_status": {
      "title": "Foto beoordeeld",
      "body": "Er is nieuws over de beoordeling van je profielfoto."
    },
    "safety_alert": {
      "title": "Veiligheidsmelding",
      "body": "Open Binder voor een melding over je account."
    },
    "product_notice": {
      "title": "Nieuw in Binder",
      "body": "Open Binder om te zien wat er is veranderd."
    }
  },
  "pl": {
    "new_match": {
      "title": "Nowy Bind!",
      "body": "Otwórz Binder, aby zobaczyć nowe dopasowanie."
    },
    "new_message": {
      "title": "Nowa wiadomość",
      "body": "Otwórz Binder, aby kontynuować rozmowę."
    },
    "moderation_status": {
      "title": "Zdjęcie sprawdzone",
      "body": "Jest wynik sprawdzenia Twojego zdjęcia profilowego."
    },
    "safety_alert": {
      "title": "Bezpieczeństwo konta",
      "body": "Otwórz Binder, aby zobaczyć informację o koncie."
    },
    "product_notice": {
      "title": "Nowości w Binderze",
      "body": "Otwórz Binder, aby zobaczyć, co się zmieniło."
    }
  },
  "pt-BR": {
    "new_match": {
      "title": "É um Bind!",
      "body": "Abra o Binder para ver seu novo match."
    },
    "new_message": {
      "title": "Nova mensagem",
      "body": "Abra o Binder para continuar a conversa."
    },
    "moderation_status": {
      "title": "Foto revisada",
      "body": "Há novidades sobre a revisão da sua foto de perfil."
    },
    "safety_alert": {
      "title": "Aviso de segurança",
      "body": "Abra o Binder para ver um aviso sobre sua conta."
    },
    "product_notice": {
      "title": "Novidades no Binder",
      "body": "Abra o Binder para ver o que mudou."
    }
  },
  "tr": {
    "new_match": {
      "title": "Bu bir Bind!",
      "body": "Yeni eşleşmenizi görmek için Binder'ı açın."
    },
    "new_message": {
      "title": "Yeni mesaj",
      "body": "Sohbete devam etmek için Binder'ı açın."
    },
    "moderation_status": {
      "title": "Fotoğraf incelendi",
      "body": "Profil fotoğrafınızın incelenmesinde yenilik var."
    },
    "safety_alert": {
      "title": "Güvenlik bildirimi",
      "body": "Hesabınızla ilgili bir bildirim için Binder'ı açın."
    },
    "product_notice": {
      "title": "Binder'da yenilikler",
      "body": "Nelerin değiştiğini görmek için Binder'ı açın."
    }
  },
  "zh-CN": {
    "new_match": {
      "title": "配对成功！",
      "body": "打开 Binder 查看你的新配对。"
    },
    "new_message": {
      "title": "新消息",
      "body": "打开 Binder 继续聊天。"
    },
    "moderation_status": {
      "title": "照片已审核",
      "body": "你的头像审核有新进展。"
    },
    "safety_alert": {
      "title": "安全提醒",
      "body": "打开 Binder 查看与你账号相关的提醒。"
    },
    "product_notice": {
      "title": "Binder 新变化",
      "body": "打开 Binder 看看有什么变化。"
    }
  }
};

export const FALLBACK_LOCALE = "en";

export function pushCopy(locale: string | null, kind: PushKind): { title: string; body: string } {
  const exact = locale ? PUSH_COPY[locale] : undefined;
  // "de-AT" should read German rather than English.
  const base = !exact && locale?.includes("-") ? PUSH_COPY[locale.split("-")[0]] : undefined;
  return (exact ?? base ?? PUSH_COPY[FALLBACK_LOCALE])[kind] ?? PUSH_COPY[FALLBACK_LOCALE][kind];
}
