// One command per shippable build: raise the version, build the signed release
// artifacts, and stage them in the release folder under a name that says which
// build they are. Nothing here talks to the store; staging is the last step
// that happens on this machine.
//
// usage: npm run release            → patch bump, APK
//        npm run release -- --bundle  → patch bump, APK + AAB for the store
//        npm run release -- --minor   → minor bump
//        npm run release -- --keep-version
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { certificateOf, writeEvidence } from './lib/release-evidence.mjs';
import { join } from 'node:path';

const root = process.cwd();
const releaseDir = process.env.BINDER_RELEASE_DIR ?? '/home/belkis/Binder-Release';
const javaHome = process.env.JAVA_HOME ?? '/home/belkis/.local/jdk/jdk-21.0.12+8';
const androidHome = process.env.ANDROID_HOME ?? '/home/belkis/Android/Sdk';

const flags = new Set(process.argv.slice(2));
const bumpKind = flags.has('--minor') ? 'minor' : flags.has('--major') ? 'major' : 'patch';
const keepVersion = flags.has('--keep-version');
const withBundle = flags.has('--bundle');

const appJsonPath = join(root, 'app.json');
const packageJsonPath = join(root, 'package.json');
const gradlePath = join(root, 'android/app/build.gradle');
// A build is only worth anything if you can say which source produced it.
//
// The evidence records the commit and whether the tree was clean, and the last
// one before this said `treeClean: false`: the artefact that would have gone to
// Play was built from a commit plus an unknown pile of uncommitted edits, and
// nothing anybody has can reproduce it. That is not a note to make on the way
// past — it is a reason not to build.
//
// The version bump this script performs is itself a change, so it commits it:
// otherwise the only way to a clean tree would be for the bump not to happen.
function gitOutput(args) {
  return execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
}

const allowDirty = flags.has('--allow-dirty');
const dirtyAtStart = gitOutput(['status', '--porcelain'])
  .split('\n')
  .map((line) => line.trim())
  .filter(Boolean);
if (dirtyAtStart.length > 0 && !allowDirty) {
  console.error('The working tree has uncommitted changes, so the build could not be reproduced from any commit:');
  for (const line of dirtyAtStart.slice(0, 20)) console.error(`  ${line}`);
  if (dirtyAtStart.length > 20) console.error(`  … and ${dirtyAtStart.length - 20} more`);
  console.error('\nCommit them (or stash them) and run this again. `--allow-dirty` builds anyway and marks the evidence.');
  process.exit(1);
}

const appJson = JSON.parse(readFileSync(appJsonPath, 'utf8'));

const currentVersion = String(appJson.expo.version);
const currentCode = Number(appJson.expo.android.versionCode);
const version = keepVersion ? currentVersion : bumpSemver(currentVersion, bumpKind);
const versionCode = keepVersion ? currentCode : currentCode + 1;

if (!keepVersion) {
  appJson.expo.version = version;
  appJson.expo.android.versionCode = versionCode;
  writeFileSync(appJsonPath, `${JSON.stringify(appJson, null, 2)}\n`);

  // scripts/verify-phase5-contract.mjs fails when these two disagree, and the
  // beta diagnostics report the app version from the package.
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
  packageJson.version = version;
  writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

  // android/ is generated by expo prebuild and gitignored, but it is not
  // regenerated for every build — so the version has to be written there too.
  const gradle = readFileSync(gradlePath, 'utf8')
    .replace(/versionCode\s+\d+/, `versionCode ${versionCode}`)
    .replace(/versionName\s+"[^"]+"/, `versionName "${version}"`);
  writeFileSync(gradlePath, gradle);
  // The README carries the version, and the gate below refuses a README that
  // no longer matches its sources. Regenerating it here keeps the bump one
  // step instead of a build that fails on its own first act.
  execFileSync(process.execPath, ['scripts/build-readme.mjs'], { stdio: 'inherit' });

  console.log(`Version ${currentVersion} (code ${currentCode}) → ${version} (code ${versionCode})`);

  // The bump is committed here so the artefact has a commit of its own to
  // point at. android/ is not in the repository, so only the four tracked
  // files are added — naming them rather than adding everything, because a
  // release build is the wrong moment to sweep up whatever else is lying
  // around.
  if (!allowDirty) {
    execFileSync('git', ['add', 'app.json', 'package.json', 'README.md'], { cwd: root, stdio: 'inherit' });
    execFileSync('git', ['commit', '-m', `Version ${version} (code ${versionCode})`], { cwd: root, stdio: 'inherit' });
    console.log(`Committed the bump as ${gitOutput(['rev-parse', '--short', 'HEAD'])}`);
  }
} else console.log(`Keeping version ${version} (code ${versionCode})`);

// android/app/build.gradle falls back to the *debug* key when
// android/keystore.properties is missing — which is exactly what happens after
// `expo prebuild --clean` wipes the folder. A debug-signed "release" looks
// finished, installs fine, and is rejected by Play; worse, it would be a
// different certificate than the one Google matches for sign-in. So the build
// refuses to start rather than producing that artefact.
const keystoreProperties = join(root, 'android/keystore.properties');
if (!existsSync(keystoreProperties)) {
  console.error(`${keystoreProperties} is missing — the build would silently sign with the debug key.`);
  console.error('Restore it (and the .jks it points at) before building a release.');
  process.exit(1);
}

// The same checks CI runs, before anything is built. A release that skips them
// is a release nobody checked; the shorter list this replaces is exactly how
// "CI is green" and "this candidate was checked" drifted apart.
if (!flags.has('--skip-gate')) {
  console.log('Quality gate: the same list CI runs.');
  execFileSync(process.execPath, [join(root, 'scripts/quality-gate.mjs')], { stdio: 'inherit' });
} else {
  // Skipping the gate must not inherit the last run's verdict. The report from
  // whatever ran before is still lying in artifacts/, and without this line the
  // evidence file would quote its PASS as if this build had earned it.
  rmSync(join(root, 'artifacts/quality-gate.json'), { force: true });
  console.log('Quality gate skipped — this build carries no gate evidence.');
}

// The generated project signs its release build with the debug key.
//
// That is what React Native's template says, and `expo prebuild --clean`
// writes it back every time: `release { signingConfig signingConfigs.debug }`.
// A debug-signed release installs, looks finished, is rejected by Play, and
// carries a certificate Google does not match for sign-in. The check below
// reads the certificate out of the finished APK and refuses to stage it — but
// only after ten minutes of building, which is the wrong place to find out.
//
// So the signing config is written into the generated file before Gradle runs,
// from android/keystore.properties, which is not in the repository and holds
// the passwords. Same reasoning as the memory settings: android/ is generated,
// so the script owns what has to be true in it.
const appGradlePath = join(root, 'android/app/build.gradle');
{
  let gradle = readFileSync(appGradlePath, 'utf8');
  if (!gradle.includes('signingConfigs.release')) {
    const releaseSigningConfig = `        release {
            def keystoreProperties = new Properties()
            keystoreProperties.load(new FileInputStream(rootProject.file('keystore.properties')))
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
        }
    }`;
    const configsClosed = /\n(\s*)\}\n(\s*)buildTypes \{/;
    if (!configsClosed.test(gradle)) {
      console.error(`${appGradlePath} does not look like the generated project — its signingConfigs block was not found.`);
      process.exit(1);
    }
    gradle = gradle.replace(configsClosed, `\n${releaseSigningConfig}\n$2buildTypes {`);
    // Only the release build type: the first `release {` in the file is the
    // signing config that was just written, and the first
    // `signingConfigs.debug` after it belongs to the *debug* build type.
    const buildTypesAt = gradle.indexOf('buildTypes {');
    const releaseTypeAt = gradle.indexOf('release {', buildTypesAt);
    const debugSigningAt = gradle.indexOf('signingConfig signingConfigs.debug', releaseTypeAt);
    if (buildTypesAt < 0 || releaseTypeAt < 0 || debugSigningAt < 0) {
      console.error(`${appGradlePath}: the release build type's signing config was not found.`);
      process.exit(1);
    }
    gradle = `${gradle.slice(0, debugSigningAt)}signingConfig signingConfigs.release${gradle.slice(debugSigningAt + 'signingConfig signingConfigs.debug'.length)}`;
    if (!gradle.includes('signingConfig signingConfigs.release')) {
      console.error(`${appGradlePath}: the release build type still points at the debug signing config.`);
      process.exit(1);
    }
    writeFileSync(appGradlePath, gradle);
    console.log('Signing: release build type wired to the upload key from android/keystore.properties');
  }
}

// Gradle needs more room than the generated project gives it.
//
// android/gradle.properties comes out of `expo prebuild` with 2 GB of heap and
// 512 MB of metaspace, and the release build does not fit: KSP and the lint
// analysis load enough classes that the daemon dies with
// "java.lang.OutOfMemoryError: Metaspace", takes the build with it, and then
// sits there refusing the next one. The file is generated, so it cannot simply
// be edited and committed — the numbers live here, next to the build that
// needs them, and are written in before every run.
const gradleProperties = join(root, 'android/gradle.properties');
const memorySettings = { 'org.gradle.jvmargs': '-Xmx4096m -XX:MaxMetaspaceSize=2048m' };
{
  let properties = readFileSync(gradleProperties, 'utf8');
  for (const [key, value] of Object.entries(memorySettings)) {
    const line = `${key}=${value}`;
    const pattern = new RegExp(`^${key.replace(/\./g, '\\.')}=.*$`, 'm');
    properties = pattern.test(properties) ? properties.replace(pattern, line) : `${properties.trimEnd()}\n${line}\n`;
  }
  writeFileSync(gradleProperties, properties);
  console.log(`Gradle memory: ${memorySettings['org.gradle.jvmargs']}`);
}

// Gradle kept a JavaScript bundle it should have rebuilt: a release built
// minutes after a locale file changed still shipped the old German strings, and
// the phone proved it while the source said otherwise. The bundle is a few
// seconds of work and the only artefact that carries every line of the app, so
// it is thrown away before every release rather than trusted.
rmSync(join(root, 'android/app/build/generated/assets/react'), { recursive: true, force: true });

const tasks = withBundle ? ['assembleRelease', 'bundleRelease'] : ['assembleRelease'];
console.log(`Gradle: ${tasks.join(' ')}`);
execFileSync('./gradlew', tasks, {
  cwd: join(root, 'android'),
  stdio: 'inherit',
  env: { ...process.env, JAVA_HOME: javaHome, ANDROID_HOME: androidHome },
});

// Trust the artefact, not the configuration: read the certificate out of the
// APK that was just produced and compare it with the upload key. This runs
// before anything is copied into the release folder — the check used to happen
// afterwards, so a wrongly signed build was already lying there under its
// final name when the script exited, ready for somebody to upload. An APK
// signed with the wrong key is rejected by Play at best and breaks Google
// sign-in for every existing install at worst.
const uploadKeySha1 = '16dfdf3e283076be74f8a9e6750ec8b82dadd2df';
const builtApk = join(root, 'android/app/build/outputs/apk/release/app-release.apk');
const apksigner = `${androidHome}/build-tools/36.0.0/apksigner`;
if (!existsSync(apksigner)) {
  console.error(`apksigner not found at ${apksigner}. A release is not staged without verifying its signature.`);
  process.exit(1);
}
const certs = execFileSync(apksigner, ['verify', '--print-certs', builtApk], {
  encoding: 'utf8',
  env: { ...process.env, JAVA_HOME: javaHome, PATH: `${javaHome}/bin:${process.env.PATH}` },
});
const sha1 = certs.match(/Signer #1 certificate SHA-1 digest:\s*([0-9a-f]+)/)?.[1];
if (sha1 !== uploadKeySha1) {
  console.error(`The APK is signed with ${sha1 ?? 'an unreadable certificate'}, not the upload key ${uploadKeySha1}.`);
  console.error('Nothing was staged. Check android/keystore.properties and the .jks it points at.');
  process.exit(1);
}
console.log(`Signature verified against the upload key (${sha1.slice(0, 12)}…).`);

mkdirSync(releaseDir, { recursive: true });
const staged = [];
stage(builtApk, `Binder-v${version}-vc${versionCode}.apk`);
if (withBundle) {
  const stagedBundle = stage(join(root, 'android/app/build/outputs/bundle/release/app-release.aab'), `Binder-v${version}-vc${versionCode}.aab`);
  // What a phone downloads, which is not what the bundle weighs: roughly half
  // of it is debug symbols and the R8 mapping, which Play keeps and never
  // ships, and the rest is split by ABI. Measured here so the number exists
  // without a Play Console login.
  execFileSync(process.execPath, [join(root, 'scripts/report-delivery-size.mjs'), stagedBundle, join(root, 'artifacts/delivery-size-report.json')], { stdio: 'inherit' });
}
// R8 renames everything, so a stack trace from the wild is unreadable without
// the map that was used for exactly this build. Play reads it out of the AAB
// by itself; this copy is for reading a crash locally with `retrace`, because
// android/app/build/ does not survive the next build.
const mappingFile = join(root, 'android/app/build/outputs/mapping/release/mapping.txt');
if (existsSync(mappingFile)) stage(mappingFile, `Binder-v${version}-vc${versionCode}-mapping.txt`);

// The dependency list is generated, never typed: npm knows exactly what went
// into this tree, and a hand-written list is out of date the day it is written.
const sbomPath = join(releaseDir, `Binder-v${version}-vc${versionCode}-sbom.cdx.json`);
try {
  const sbom = execFileSync('npm', ['sbom', '--sbom-format', 'cyclonedx', '--omit', 'dev'], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  writeFileSync(sbomPath, sbom);
  staged.push(`${(statSync(sbomPath).size / 1024).toFixed(0)} KB  ${sbomPath}`);
} catch (error) {
  console.error(`Could not produce an SBOM: ${error instanceof Error ? error.message : error}`);
  process.exit(1);
}

// The artefact is the evidence: hashes, the certificate the file actually
// carries, the lockfile it was built from, and the gate that ran for it.
const { target: evidencePath, evidence } = writeEvidence({
  root,
  version,
  versionCode,
  artefacts: [
    join(releaseDir, `Binder-v${version}-vc${versionCode}.apk`),
    join(releaseDir, `Binder-v${version}-vc${versionCode}.aab`),
    join(releaseDir, `Binder-v${version}-vc${versionCode}-mapping.txt`),
    sbomPath,
  ],
  certificate: certificateOf(builtApk, apksigner, { ...process.env, JAVA_HOME: javaHome, PATH: `${javaHome}/bin:${process.env.PATH}` }),
  sbomPath,
});
console.log(`\nRelease evidence: ${evidencePath}`);
console.log(`  commit ${evidence.commit.slice(0, 8)}${evidence.treeClean ? '' : ' (working tree not clean)'} · gate ${evidence.qualityGate?.status ?? 'not run'} · ${evidence.artefacts.length} artefacts hashed`);

console.log('\nStaged in the release folder:');
for (const line of staged) console.log(`  ${line}`);

function stage(source, name) {
  const target = join(releaseDir, name);
  copyFileSync(source, target);
  staged.push(`${(statSync(target).size / 1024 / 1024).toFixed(2)} MB  ${target}`);
  return target;
}

function bumpSemver(value, kind) {
  const [major = 0, minor = 0, patch = 0] = value.split('.').map(Number);
  if (kind === 'major') return `${major + 1}.0.0`;
  if (kind === 'minor') return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

// Keep the folder from growing without bound: newest twenty plus the first.
execFileSync(process.execPath, [join(root, 'scripts/prune-releases.mjs')], { stdio: 'inherit' });
