// One command per shippable build: raise the version, build the signed release
// artifacts, and stage them in the release folder under a name that says which
// build they are. Nothing here talks to the store; staging is the last step
// that happens on this machine.
//
// usage: npm run release            → patch bump, APK
//        npm run release -- --bundle  → patch bump, APK + AAB for the store
//        npm run release -- --minor   → minor bump
//        npm run release -- --keep-version
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const releaseDir = process.env.BINDER_RELEASE_DIR ?? '/home/belkis/Binder-Release';
const javaHome = process.env.JAVA_HOME ?? '/home/belkis/.local/jdk/jdk-21.0.12+8';
const androidHome = process.env.ANDROID_HOME ?? '/home/belkis/Android/Sdk';

const flags = new Set(process.argv.slice(2));
const bumpKind = flags.has('--minor') ? 'minor' : flags.has('--major') ? 'major' : 'patch';
const keepVersion = flags.has('--keep-version');
const withBundle = flags.has('--bundle');

const appJsonPath = join(root, 'app.json');
const packageJsonPath = join(root, 'package.json');
const gradlePath = join(root, 'android/app/build.gradle');
const appJson = JSON.parse(readFileSync(appJsonPath, 'utf8'));

const currentVersion = String(appJson.expo.version);
const currentCode = Number(appJson.expo.android.versionCode);
const version = keepVersion ? currentVersion : bumpSemver(currentVersion, bumpKind);
const versionCode = keepVersion ? currentCode : currentCode + 1;

if (!keepVersion) {
  appJson.expo.version = version;
  appJson.expo.android.versionCode = versionCode;
  writeFileSync(appJsonPath, `${JSON.stringify(appJson, null, 2)}\n`);

  // scripts/verify-phase5-contract.mjs fails when these two disagree, and the
  // beta diagnostics report the app version from the package.
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
  packageJson.version = version;
  writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

  // android/ is generated by expo prebuild and gitignored, but it is not
  // regenerated for every build — so the version has to be written there too.
  const gradle = readFileSync(gradlePath, 'utf8')
    .replace(/versionCode\s+\d+/, `versionCode ${versionCode}`)
    .replace(/versionName\s+"[^"]+"/, `versionName "${version}"`);
  writeFileSync(gradlePath, gradle);
  console.log(`Version ${currentVersion} (code ${currentCode}) → ${version} (code ${versionCode})`);
} else console.log(`Keeping version ${version} (code ${versionCode})`);

const tasks = withBundle ? ['assembleRelease', 'bundleRelease'] : ['assembleRelease'];
console.log(`Gradle: ${tasks.join(' ')}`);
execFileSync('./gradlew', tasks, {
  cwd: join(root, 'android'),
  stdio: 'inherit',
  env: { ...process.env, JAVA_HOME: javaHome, ANDROID_HOME: androidHome },
});

mkdirSync(releaseDir, { recursive: true });
const staged = [];
stage(join(root, 'android/app/build/outputs/apk/release/app-release.apk'), `Binder-v${version}-vc${versionCode}.apk`);
if (withBundle) stage(join(root, 'android/app/build/outputs/bundle/release/app-release.aab'), `Binder-v${version}-vc${versionCode}.aab`);

console.log('\nStaged in the release folder:');
for (const line of staged) console.log(`  ${line}`);

function stage(source, name) {
  const target = join(releaseDir, name);
  copyFileSync(source, target);
  staged.push(`${(statSync(target).size / 1024 / 1024).toFixed(2)} MB  ${target}`);
}

function bumpSemver(value, kind) {
  const [major = 0, minor = 0, patch = 0] = value.split('.').map(Number);
  if (kind === 'major') return `${major + 1}.0.0`;
  if (kind === 'minor') return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}
