// One command per shippable build: raise the version, build the signed release
// artifacts, and stage them in the release folder under a name that says which
// build they are. Nothing here talks to the store; staging is the last step
// that happens on this machine.
//
// usage: npm run release            → patch bump, APK
//        npm run release -- --bundle  → patch bump, APK + AAB for the store
//        npm run release -- --minor   → minor bump
//        npm run release -- --keep-version
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const releaseDir = process.env.BINDER_RELEASE_DIR ?? '/home/belkis/Binder-Release';
const javaHome = process.env.JAVA_HOME ?? '/home/belkis/.local/jdk/jdk-21.0.12+8';
const androidHome = process.env.ANDROID_HOME ?? '/home/belkis/Android/Sdk';

const flags = new Set(process.argv.slice(2));
const bumpKind = flags.has('--minor') ? 'minor' : flags.has('--major') ? 'major' : 'patch';
const keepVersion = flags.has('--keep-version');
const withBundle = flags.has('--bundle');

const appJsonPath = join(root, 'app.json');
const packageJsonPath = join(root, 'package.json');
const gradlePath = join(root, 'android/app/build.gradle');
const appJson = JSON.parse(readFileSync(appJsonPath, 'utf8'));

const currentVersion = String(appJson.expo.version);
const currentCode = Number(appJson.expo.android.versionCode);
const version = keepVersion ? currentVersion : bumpSemver(currentVersion, bumpKind);
const versionCode = keepVersion ? currentCode : currentCode + 1;

if (!keepVersion) {
  appJson.expo.version = version;
  appJson.expo.android.versionCode = versionCode;
  writeFileSync(appJsonPath, `${JSON.stringify(appJson, null, 2)}\n`);

  // scripts/verify-phase5-contract.mjs fails when these two disagree, and the
  // beta diagnostics report the app version from the package.
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'));
  packageJson.version = version;
  writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 2)}\n`);

  // android/ is generated by expo prebuild and gitignored, but it is not
  // regenerated for every build — so the version has to be written there too.
  const gradle = readFileSync(gradlePath, 'utf8')
    .replace(/versionCode\s+\d+/, `versionCode ${versionCode}`)
    .replace(/versionName\s+"[^"]+"/, `versionName "${version}"`);
  writeFileSync(gradlePath, gradle);
  console.log(`Version ${currentVersion} (code ${currentCode}) → ${version} (code ${versionCode})`);
} else console.log(`Keeping version ${version} (code ${versionCode})`);

// android/app/build.gradle falls back to the *debug* key when
// android/keystore.properties is missing — which is exactly what happens after
// `expo prebuild --clean` wipes the folder. A debug-signed "release" looks
// finished, installs fine, and is rejected by Play; worse, it would be a
// different certificate than the one Google matches for sign-in. So the build
// refuses to start rather than producing that artefact.
const keystoreProperties = join(root, 'android/keystore.properties');
if (!existsSync(keystoreProperties)) {
  console.error(`${keystoreProperties} is missing — the build would silently sign with the debug key.`);
  console.error('Restore it (and the .jks it points at) before building a release.');
  process.exit(1);
}

// Gradle kept a JavaScript bundle it should have rebuilt: a release built
// minutes after a locale file changed still shipped the old German strings, and
// the phone proved it while the source said otherwise. The bundle is a few
// seconds of work and the only artefact that carries every line of the app, so
// it is thrown away before every release rather than trusted.
rmSync(join(root, 'android/app/build/generated/assets/react'), { recursive: true, force: true });

const tasks = withBundle ? ['assembleRelease', 'bundleRelease'] : ['assembleRelease'];
console.log(`Gradle: ${tasks.join(' ')}`);
execFileSync('./gradlew', tasks, {
  cwd: join(root, 'android'),
  stdio: 'inherit',
  env: { ...process.env, JAVA_HOME: javaHome, ANDROID_HOME: androidHome },
});

// Trust the artefact, not the configuration: read the certificate out of the
// APK that was just produced and compare it with the upload key. This runs
// before anything is copied into the release folder — the check used to happen
// afterwards, so a wrongly signed build was already lying there under its
// final name when the script exited, ready for somebody to upload. An APK
// signed with the wrong key is rejected by Play at best and breaks Google
// sign-in for every existing install at worst.
const uploadKeySha1 = '16dfdf3e283076be74f8a9e6750ec8b82dadd2df';
const builtApk = join(root, 'android/app/build/outputs/apk/release/app-release.apk');
const apksigner = `${androidHome}/build-tools/36.0.0/apksigner`;
if (!existsSync(apksigner)) {
  console.error(`apksigner not found at ${apksigner}. A release is not staged without verifying its signature.`);
  process.exit(1);
}
const certs = execFileSync(apksigner, ['verify', '--print-certs', builtApk], {
  encoding: 'utf8',
  env: { ...process.env, JAVA_HOME: javaHome, PATH: `${javaHome}/bin:${process.env.PATH}` },
});
const sha1 = certs.match(/Signer #1 certificate SHA-1 digest:\s*([0-9a-f]+)/)?.[1];
if (sha1 !== uploadKeySha1) {
  console.error(`The APK is signed with ${sha1 ?? 'an unreadable certificate'}, not the upload key ${uploadKeySha1}.`);
  console.error('Nothing was staged. Check android/keystore.properties and the .jks it points at.');
  process.exit(1);
}
console.log(`Signature verified against the upload key (${sha1.slice(0, 12)}…).`);

mkdirSync(releaseDir, { recursive: true });
const staged = [];
stage(builtApk, `Binder-v${version}-vc${versionCode}.apk`);
if (withBundle) stage(join(root, 'android/app/build/outputs/bundle/release/app-release.aab'), `Binder-v${version}-vc${versionCode}.aab`);
// R8 renames everything, so a stack trace from the wild is unreadable without
// the map that was used for exactly this build. Play reads it out of the AAB
// by itself; this copy is for reading a crash locally with `retrace`, because
// android/app/build/ does not survive the next build.
const mappingFile = join(root, 'android/app/build/outputs/mapping/release/mapping.txt');
if (existsSync(mappingFile)) stage(mappingFile, `Binder-v${version}-vc${versionCode}-mapping.txt`);

console.log('\nStaged in the release folder:');
for (const line of staged) console.log(`  ${line}`);

function stage(source, name) {
  const target = join(releaseDir, name);
  copyFileSync(source, target);
  staged.push(`${(statSync(target).size / 1024 / 1024).toFixed(2)} MB  ${target}`);
}

function bumpSemver(value, kind) {
  const [major = 0, minor = 0, patch = 0] = value.split('.').map(Number);
  if (kind === 'major') return `${major + 1}.0.0`;
  if (kind === 'minor') return `${major}.${minor + 1}.0`;
  return `${major}.${minor}.${patch + 1}`;
}

// Keep the folder from growing without bound: newest twenty plus the first.
execFileSync(process.execPath, [join(root, 'scripts/prune-releases.mjs')], { stdio: 'inherit' });
